version: '3'
services:
  app:
    image: my-app
    restart: unless-stopped
    build:
      context: .
    ports:
      - "80:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"